### ISSUE TITLE
🎃💻 Update README.md to mark this project as EOL [claimed by sgoblin]

### ISSUE THREAD

**Issue by bootstraponline** [instructure/CanvasKit#230]
## 🎃💻 Hacktoberfest

Sign up to [hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn a T-Shirt 👕.

## 📖 Rules

Comment on this issue to claim the task. If someone already claimed the task, then locate another hacktoberfest issue to work on. 😄 

## 🎯 Goal

Submit a pull request that updates the `README.md` to state this project is end of life.

**Comment by sgoblin** [comment]
Task claimed.

**Comment by bootstraponline** [comment]
Thanks. I updated the title to reflect that you've claimed the task.

**Comment by bootstraponline** [comment]
Fixed by https://github.com/instructure/CanvasKit/issues/231
